### ISSUE TITLE
plese make a little change in the setup user guide

### ISSUE THREAD

**Issue by ncgege** [kbs1/openxdagpool#1]
1.utg8mb4_unicode_ci   is not correct may be utf8mb4_unicode_ci
2.the xdag new version  do not exist cheatcoin dir . it changed to client.
thank you.

**Comment by kbs1** [comment]
Hello, updated, thank you. Please view current active repository at https://github.com/XDagger/openxdagpool, this repo is no longer maintained.

**Comment by ncgege** [comment]
Thank you for your efficient work.
